moving workflow to correct location

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -8,3 +8,12 @@ jobs:
         steps:
             - name: Say hello
               run: echo "Hello World"
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Failed step
+              run: |
+                echo "I will fail"
+                exit 1
+            - name: Say goodbye
+              run: echo "Goodbye!"
